//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobMegaChallenge.Persistence
{
    using System;
    
    public enum Crust : int
    {
        Regular = 0,
        Thin = 1,
        Thick = 2
    }
}
