//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobMegaChallenge.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PizzaPriceTable
    {
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public double SmallSizeCost { get; set; }
        public double MediumSizeCost { get; set; }
        public double LargeSizeCost { get; set; }
        public double ThickCrustCost { get; set; }
        public double ThinCrustCost { get; set; }
        public double PepperoniCost { get; set; }
        public double SausageCost { get; set; }
        public double GreenPeppersCost { get; set; }
        public double OnionsCost { get; set; }
    }
}
